name: Playwright MCP CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: 
          node-version: 18

      - name: Install deps
        run: npm ci

      - name: Install axios
        run: npm install axios

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Install ts-node and TypeScript
        run: npm install --save-dev ts-node typescript

      - name: Run MCP-driven Claude automation
        run: node --loader ts-node/esm mcp-runner.ts
        continue-on-error: false

      - name: Upload Playwright videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-videos
          path: test-results/**/video/*.webm

      - name: Upload logs on failure
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: mcp-claude-logs
          path: logs/